### ISSUE TITLE
[linux] pressing B to change weapon infinite cycle

### ISSUE THREAD

**Issue by arrowgent** [alexbatalov/fallout1-ce#19]
at some point _pressing B to change your weapon_ (as the F1 help menu shows) will **infinite loop** change weapons and you cant stop it, move, exit, or otherwise
have to alt-f4 the game (or ctrl-c the terminal)

**Comment by M1sh2** [comment]
The same error on win 64 build.

**Comment by alexbatalov** [comment]
Any clues to reproduce it?

**Comment by NukeItAll** [comment]
Had it on android also when i had my keyboard plugged in. Not sure how to reproduce it. Happend in necropolis when seth started attacken me after a conversation and i wanted to switch weapons

**Comment by M1sh2** [comment]
> Any clues to reproduce it?

The error is very easy to reproduce if you pick up a weapon (gun) at the beginning, enter combat mode, change weapons. The character will constantly change weapons, I went through the whole game with this bug, just without changing the game through B or on the button in the menu.

**Comment by alexbatalov** [comment]
The fix is on par with F2, but strictly speaking key handling code is slightly wrong in both F2CE and F1CE. Original game does not poll DirectInput for next key when keyboard is disabled, so events are accumulated in DirectInput internal buffers. In CE events are polled via SDL and filtered afterwards, so when keyboard is disabled in the middle of key-down/key-up pair of events, next key-up event is silently ignored. This leads the game to think we're still holding the key. In this case B in combat mode - it starts modal animation for switching weapons which disables game UI for a couple of seconds and then re-enables it back. Since the game thinks B is still being held, it performs switching over and over again.
