### ISSUE TITLE
Heavy Handed -30% penalty is not used in combat

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout1-ce#58]
The penalty is not actually used in the calculation? I don't know if this is vanilla behavior. Would be quite funny if it was :)

https://github.com/alexbatalov/fallout1-ce/blob/406b69b0fc52b53608cc34782ca9976c8b2b9c3e/src/game/combat.cc#L3061

**Comment by emxd** [comment]
This seems to be the culprit
https://github.com/alexbatalov/fallout1-ce/blob/406b69b0fc52b53608cc34782ca9976c8b2b9c3e/src/game/stat.cc#L208

**Comment by alexbatalov** [comment]
You're right. I've checked v1.1 and v1.2 of original Fallout binaries, the problem is that "Better Criticals" stat's minimal value is 0. Heavy Handed penalize this stat below 0 (to -30), but it cannot bypass `clamp` guard. In Fallout 2 minimal value for "Better Criticals" stat is -60, so there is no such bug.
